---
title: Coventry University Mountaineering Society
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: edward_prince@hotmail.com
description: 'This is the website for Coventry Universities Mountaineering Society.
  Here you can find an abundance of information, pictures and more to  view.

'
baseurl: ''
url: http://edprince.github.io
twitter_username: jekyllrb
github_username: edprince
markdown: kramdown
